apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-keda-poc-consumer
  namespace: default
spec:
  # -------------------------------------------------------------------
  # KEDA MAGIC: We start with absolutely 0 pods running. 
  # KEDA will override this when it detects messages in GCP.
  # -------------------------------------------------------------------
  replicas: 0 
  selector:
    matchLabels:
      app: keda-poc-consumer
  template:
    metadata:
      labels:
        app: keda-poc-consumer
    spec:
      containers:
      - name: poc-consumer
        # Build the python app in ../consumer/Dockerfile and push to your ECR
        image: 487500748616.dkr.ecr.us-east-1.amazonaws.com/keda-poc-worker:latest
        imagePullPolicy: Always
        env:
          - name: GCP_PROJECT_ID
            value: "wired-sign-858"
          - name: GCP_SUBSCRIPTION_ID
            value: "keda-poc-sub"
          
          # Inject the same GCP Key into the pod so the python SDK can pull messages
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/var/secrets/google/GoogleApplicationCredentials"
            
        volumeMounts:
        - name: gcp-key-volume
          mountPath: /var/secrets/google
          readOnly: true
          
      volumes:
      - name: gcp-key-volume
        secret:
          secretName: gcp-keda-auth-secret
