apiVersion: v1
kind: ConfigMap
metadata:
  name: gcp-multi-topic-configmap
  namespace: default
data:
  topics.json: |
    {
      "topics": [
        "projects/wired-sign-858/subscriptions/keda-poc-sub"
      ]
    }
